### ISSUE TITLE
Wrong report about software GL implementation

### ISSUE THREAD

**Issue by vanfanel** [chocolate-doom/chocolate-doom#1012] opened 2018-03-31 14:41 UTC
Hi there,

I have seen this piece of code in src/i_video.c:
```

static void CheckGLVersion(void)
{
    const char * version;
    typedef const GLubyte* (APIENTRY * glStringFn_t)(GLenum);
    glStringFn_t glfp = (glStringFn_t)SDL_GL_GetProcAddress("glGetString");

    if (glfp)
    {    
        version = (const char *)glfp(GL_VERSION);

        if (version && strstr(version, "Mesa"))
        {
            printf("%s", hw_emu_warning);
        }
    }    
}

```

It assumes MESA is always software, which is plainly wrong: VC4 (Raspberry Pi), Freedreno and most/all Intel have hardware GL/GLES support in MESA. So the warning being displayed with ANY MESA implementation is not right I believe.

**Comment by jmtd** [comment] 2018-03-31 17:25
This is a duplicate of #825

**Closed by jmtd** 2018-03-31 17:25 UTC
