### ISSUE TITLE
Fullscreen Setup + endoom + loading screen

### ISSUE THREAD

**Issue by TheElf01** [chocolate-doom/chocolate-doom#1239] opened 2020-01-12 02:14 UTC
Hi,  sorry if i ask a question was already answer, but im new with this port, and i did not find any answer to my questions

Im using latest version of chocolate doom, windows XP,  i have some questions

1 - I cant find a way to open the setup in fullscreen, is always in a window.. i dont know if is a bug, or i miss a command line (i tested -fullscreen, but no luck)

2 - When i close Doom, the endoom screen shows... but in a window... maybe is a bug,  the normal is to show in fullscreen, then go back to command line

3 - the ldoom loading screen is not present... any way to show? i read the command line txt, but did not find anything

![IBc00](https://user-images.githubusercontent.com/16392474/72213116-89137700-34e9-11ea-8422-919d79743aec.png)

thanks

**Comment by chungy** [comment] 2020-01-12 08:42
the libtextscreen library used to emulate VGA text mode for the setup program and ENDOOM doesn't support fullscreen and it's not a feature planned to be implemented.

The initialization/message texts require stdout/stderr to be connected to something, which is not default on Windows; some alternate terminals like provided on cygwin and msys2 (which don't run on XP anymore) will connect these file descriptors to the terminal and it will show, but you won't get it through cmd.exe.

**Comment by TheElf01** [comment] 2020-01-12 14:33
> 
> 
> the libtextscreen library used to emulate VGA text mode for the setup program and ENDOOM doesn't support fullscreen and it's not a feature planned to be implemented.
> 
> The initialization/message texts require stdout/stderr to be connected to something, which is not default on Windows; some alternate terminals like provided on cygwin and msys2 (which don't run on XP anymore) will connect these file descriptors to the terminal and it will show, but you won't get it through cmd.exe.

thanks for reply,  i think i misunderstood the project, because i read "is a Doom source port that accurately reproduces the experience of Doom"  i believe was a about everything, not just ingame

I load chocolate doom from cygwin and msys2, and yes, i manage to output the loading screen. Not practical anyways, but curious

>                          Chocolate Doom 3.0.0
Z_Init: Init zone memory allocation daemon. 
zone memory: 03BF0020, 1000000 allocated for zone
V_Init: allocate screens.
M_LoadDefaults: Load system defaults.
saving config in default.cfg
W_Init: Init WADfiles.
 adding doom.wad
===========================================================================
                           The Ultimate DOOM
===========================================================================
 Chocolate Doom is free software, covered by the GNU General Public
 License.  There is NO warranty; not even for MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. You are welcome to change and distribute
 copies under certain conditions. See the source for more information.
===========================================================================
I_Init: Setting up machine state.
OPL_Init: Using driver 'SDL'.
NET_Init: Init network subsystem.
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - ..........................
P_Init: Init Playloop state.
S_Init: Setting up sound.
D_CheckNetGame: Checking network game status.
startskill 2  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
Emulating the behavior of the 'Ultimate Doom' executable.
HU_Init: Setting up heads up display.
ST_Init: Init status bar.

thanks for reply

**Comment by fragglet** [comment] 2020-01-13 16:45
Thanks for the report and feature request.

There are essentially three separate feature requests here and I'll address each of them:

1. "Can't open setup fullscreen" - this is deliberate, ie. setup itself by design does not have any settings. The project takes a stance of deliberately avoiding unnecessary settings.

2. "Can't make ENDOOM show fullscreen" - in theory it would be possible to add a setting for this, but it would be so obscure as a setting that I'd prefer not to add it.

3. "Text loading screen is not shown" - if you use Linux or macOS (or anything except Windows), it actually is shown on the console. SDL's Windows startup hooks take over the standard output so this is difficult to achieve. It seems like you've managed to figure out how to do this with MSYS/Cygwin already though so maybe you're happy.

Given the above responses I'm going to close this issue.

**Closed by fragglet** 2020-01-13 16:45 UTC

**Comment by drfrag666** [comment] 2020-03-06 14:06
So you're that guy from the spanish testingzone? forum. It's curious that another user reported Choco not running on XP in another issue. RUDE has a startup console and that's the engine i want to use in the extreme multiplayer event i announced in that forum (i'm dondiego) but there was a serious problem.
