### ISSUE TITLE
[2.2.1 / Heretic] Bug with pickup messages

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#781] opened 2016-10-10 16:44 UTC
Dear Simon, Dear Colleagues,
Guess, I have found a little but annoying bug with pickup messages.

Situation: Messages are ON in options menu. I'm playing any level normally for 5-10 minutes, i.e. killing monsters picking up items, everything is fine. Next, I'm finishing level, and when new level starts, there is NO pickup messages, when I’m pickup something. To make them show again, it is necessary to simply press ESC two times (enter and exit menu).

Thoughts: I was trying to repeat this case with saving/loading - no result. Looks likes, it is necessary to spent real 5-10 minutes on level, receive some pickup messages, then go to next level - and only then this bug will appear.

Situation seems like there is some kind of timer, that disables messages on next level.
I was trying to figure out / fix it in sources of 2.2.1 -- no luck (lack of experience), but correct displaying of messages is critical for me, since I'm working on Russian translation.

if necessary, I will try to record video.

**Comment by CapnClever** [comment] 2016-10-10 23:03
As an initial test (in 2.2.1), I started the first level, left it sitting for ten minutes, then completed the level: this did not cause messages to disappear on the next level. Then I continued playing through the whole of episode 1, still no problem. I did my best to play through each level casually, so every level was at least 5-10min.

I vaguely recall this happening before, (though I didn't think anything of it at the time) so I'll continue testing cases in an attempt to reproduce. @JNechaevsky, if you can reproduce the issue consistently, a video would be helpful.

**Comment by CapnClever** [comment] 2016-10-11 01:56
@JNechaevsky explained to me on IRC that the "bug with messages happens if I save the game just before end of level". I was able to reproduce the bug under these conditions:

1. Start new game
2. Save game
3. Exit level before "saved game" disappears from messages (either through normal exit or via `engage##` code)
4. Pick up an item, note that message does not appear
5. Open up menu, then close it
6. Pick up another item, note that message does appear

The offending function is `P_SetMessage()`: from the look of it, the "saved game" message suppresses other messages (via an `ultmsg` argument) until cleared. Could be that exiting the level before the clearing messes with expected handling.

Anyway, more to the point of Chocolate, I was also able to reproduce this bug in vanilla Heretic via DOSBox. I don't think this falls under consideration to fix: it's also incredibly easy for the player to fix it themselves.

**Comment by JNechaevsky** [comment] 2016-10-11 09:03
**@CapnClever**, I was thinking that this is some kind of text buffer problem, but now I see that I was completely wrong. :) Thank you **very much** for investigation and explanation! Guess, there is no need to make an video now.

As you pointed, I have fixed this case for myself by simple stricting _ultimatemsg_ to _false_ in p_inter.c:
```
    if (ultmsg)
    {
        ultimatemsg = false; 
    }
```
Not exactly a professional and right way, but it completely covers all my translation needs and this is the best I can do, since I'm not programmer. After compiling and testing by your way, everything becomes okay: 
[https://youtu.be/5f52XzhEgIc](https://youtu.be/5f52XzhEgIc)

I'm also agreed that maybe it is better to left this Raven's bug-feature "as is" to comply Chocolate philosophy.

**Comment by haleyjd** [comment] 2016-10-11 16:47
Going to mark this one as closed due to recognition that it's accurate vanilla behavior; thanks.

**Closed by haleyjd** 2016-10-11 16:47 UTC
Labels: Heretic, invalid
