### ISSUE TITLE
Can't save in chocolate strife 

### ISSUE THREAD

**Issue by NuclearCrow** [chocolate-doom/chocolate-doom#568] opened 2015-07-01 17:30 UTC
I can't save, every time i save it shows that the game was saved, but when i go to the load screen no files are present.

**Comment by fx02** [comment] 2015-07-01 23:48
Try this, left click on chocolate-strife.exe and run as administrator.

**Comment by NuclearCrow** [comment] 2015-07-02 05:17
I am using Windows XP, i always run as an administrator...

**Comment by fx02** [comment] 2015-07-02 18:13
Close strife after save then opet stdout.txt and stderr.txt and paste the contents here.

**Comment by NuclearCrow** [comment] 2015-07-02 21:56
I can't find them, they are not in the folder.

**Comment by chungy** [comment] 2015-07-02 22:44
Could you shed a little more details about how you installed Strife and Chocolate Doom?

**Comment by NuclearCrow** [comment] 2015-07-03 05:24
I basically extracted it on my desktop, added strife1.wad + voices.wad, and i run it by double clicking chocolate-strife.exe

**Comment by fx02** [comment] 2015-07-03 15:21
Well, try to move everything somewhere else from desktop, I'm not sure if it's smart to run from desktop, never tried it :)  eg. create c:\games\doom or d:\doom and extract it there then see if it works.

ps. just tried to run it from desktop and it works heh, but to be sure do as I suggested

**Comment by NuclearCrow** [comment] 2015-07-12 16:04
Well thanks, that did actually fix the issue, but i have no idea how...

**Comment by fragglet** [comment] 2015-07-12 17:12
Does your Windows username include a space in it? For example, "Nuclear Crow" rather than "NuclearCrow"?

**Comment by NuclearCrow** [comment] 2015-07-12 17:16
It doesn't it has an underscore in between, but the issue is fixed now, it was probably the game not being able to locate the save files...

**Comment by fragglet** [comment] 2015-07-12 17:20
I want to understand why the game couldn't find the game files in the first place. It sounds like a bug.

**Comment by NuclearCrow** [comment] 2015-07-12 17:24
Maybe it has a preset path like C:/Chocolatedoom... ect. and me putting it on the desktop and running it saved the files into that preset directory, but i don't know.

**Comment by chungy** [comment] 2015-07-12 18:43
It should work in the current directory regardless of where it's put.

**Comment by NuclearCrow** [comment] 2015-07-12 18:46
Well explain that to the game, i might have few system bugs myself, i have an outdated windows xp system with a lot of mods and tweaks, so it might be a problem on my side...

**Comment by chungy** [comment] 2015-07-12 18:47
Can you describe your setup any better? Such as what the full path (including drive letter and all directories leading up to it) to the game is?

**Comment by NuclearCrow** [comment] 2015-07-12 18:49
My old path: E:\Documents and Settings\Damian Schwub\Desktop\Hry\Střílečky\chocolate-strife-2.2.0-win32
New (working) path: C:\chocolate-strife-2.2.0-win32

**Comment by chungy** [comment] 2015-07-12 18:50
It is probably the "Střílečky" part that the program choked up over.

**Comment by NuclearCrow** [comment] 2015-07-12 18:52
Well now we know the core of the problem...

**Comment by fx02** [comment] 2015-07-12 20:02
It should not "choke" on that, but if it did, that should be fixed.

**Comment by fabiangreffrath** [comment] 2015-07-13 07:00
`E:\Documents and Settings\Damian Schwub\Desktop\Hry\Střílečky\chocolate-strife-2.2.0-win32`
Spaces ^ ^ ^

**Comment by chungy** [comment] 2015-07-13 07:14
Spaces should be ok. It's worked on Windows XP under "Documents and Settings" for many other users, with only the lower ASCII characters.

**Comment by fragglet** [comment] 2015-07-13 07:25
I think the non-ASCII characters are almost certainly the problem here.

**Comment by chungy** [comment] 2015-07-13 08:12
Should be noted that Windows doesn't enforce a character encoding for file names, it assumes a locale default most of the time. If you test this, it would be worth trying both the utf-8 version and whatever locale Czech would be (CP850?). Cygwin would probably make it easier to create names with explicit sequences of bytes (`mkdir $(printf \xef...)` for example), though probably want to check the cygwin docs for how they handle things.

**Comment by haleyjd** [comment] 2015-07-14 18:10
Windows C runtime file IO functions are not safe for paths with Unicode characters in them, AFAIK.

**Comment by chungy** [comment] 2016-08-24 05:05
I've attempted to reproduce this using the Czech version of Windows XP, and cannot get saving to fail based on file names. I used both Windows Explorer to create a "Střílečky" folder (saves as UTF-16), and Cygwin to create a folder with `mkdir "$(printf 'St\xfd\xa1le\x9fky')"` (forces the CP852 code page -- otherwise, Cygwin would create UTF-16 names too). Even in the latter example, Windows Explorer displayed boxes for the non-ASCII characters, but Chocolate Strife still had no problems saving in the path.

I do wonder if there were file system permission errors happening. I notice you had both E:\ and C:\ in use. If E:\ is the NTFS volume of a Windows installation that's not the one running, these kind of errors would be expected, because your user IDs would not match between the two installs (being Administrator won't change file system security taking place). If this is the case, the file name encoding is just a red herring, and perhaps b664c5871c6c0e66e324952b7d756c3bc28b7bf9 would help a bit. It also wouldn't really be a Chocolate Doom bug ;)

**Comment by chungy** [comment] 2017-09-06 21:36
Re-reading this long thread and with a lack of new responses, I strongly suspect this was related to file system permissions or some other OS configuration issue unrelated to Chocolate Doom, especially given my prior lack of being able to reproduce it. Closing.

**Closed by chungy** 2017-09-06 21:36 UTC
Labels: Strife, windows
