### ISSUE TITLE
Plutonia 2 demo playback crash

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#746] opened 2016-07-10 20:31 UTC
Plutonia 2's first demo consistently crashes (closes to desktop) chocolate-doom-2.2.1-win32.zip as well as chocolate-doom-20160710-win32.zip, even on default, unmodified settings. It happens very early on in the playback and leaves no trace of what went wrong (no errors in message boxes, log files or command line)

http://www.rabotik.nl/plutonia2/htmls/down.htm

Tested on the 32-bit version of Windows XP Professional Service Pack 3, everything up to date and working as intended system-wise.

Double-checked with DosBox and it won't crash.

Best regards.

**Comment by chungy** [comment] 2016-07-10 20:51
Duplicate of #66

**Closed by chungy** 2016-07-10 20:51 UTC
