### ISSUE TITLE
Player spawns under the floor when starting a DM2.0 game with HMP difficulty on Gothic2.wad MAP32

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#873] opened 2017-02-28 15:25 UTC
When starting a DM2.0 game with HMP difficulty on Gothic2.wad MAP32 https://www.doomworld.com/idgames/levels/doom2/deathmatch/megawads/gothic2 the player spawns under the floor. If the dufficulty is UV or NM, the player spawns correctly.
This WAD is designed for Vanilla Doom, so anyone who can run VD please test this to find out if the same happens in Vanilla.
There is some mysterious paragraph in the WAD description that may be related to this
Difficulty Settings: Yes (1-3 New 2.0, 4-5 Old 1.0)
but to me it's insufficient to explain what exactly happens.

**Comment by jmtd** [comment] 2017-02-28 17:27
tagging 'confirmed' but I'm not sure what vanilla behaviour is yet

**Comment by jmtd** [comment] 2017-02-28 17:33
The sector that DM start is sitting in has a lower floor than the surrounding areas and no textures on the lower sidedefs. It's probably a special effect, designed so that you can have the surrounding floor light level flood over that but the ceiling will be lit up different. At least that's the result. You can't fall in from outside because it's too small for clipping but if your origin is in there, you're stuck. I think that if you play a full DM game on any skill level you will occasionally spawn in there.

**Comment by jmtd** [comment] 2017-02-28 17:33
closing since we match vanilla here

**Closed by jmtd** 2017-02-28 17:33 UTC
Labels: confirmed, Doom

**Comment by AXDOOMER** [comment] 2017-02-28 18:27
It's weird that it would changed based on the skill level. I haven't tested, but this is what Doom Builder shows. 

![](https://s4.postimg.org/7mekxnnzx/3232.png)

**Comment by Zodomaniac** [comment] 2017-02-28 18:34
So finally this turns out to be a level design bug.
