### ISSUE TITLE
Sound effects are somewhat muffled in latest build

### ISSUE THREAD

**Issue by cubebert-github** [chocolate-doom/chocolate-doom#1310] opened 2020-09-03 01:08 UTC
I've recently compiled a working build of Chocolate Doom with the latest commit (f700744) and I've noticed that compared to the latest stable build of Chocolate Doom (3.0.1), the digital sound effects are somewhat muffled. I've tested this with only the stock doom2.wad file and no additional wads being loaded. I'm using Windows 7 64-bit for my operating system if that helps with anything; I recommend that the sound volume in-game is maxed out on both builds so that it can be more easily heard. I'm new to using GitHub, but I'll try to provide more information if it's needed.

**Comment by QuartzSTQ** [comment] 2023-05-30 00:04
I have this issue as well, but it's on the 3.0.1 build as well as the [autobuilds](http://latest.chocolate-doom.org/), and the strangest thing is that it's not present at all when using Crispy Doom, not even when using the autobuilds.

To me it seems to be using differing interpolation, and I think what's happening is that it's defaulting to a technically higher-quality option, but one that isn't accurate to how the audio should sound in actual Doom.

**Comment by ceski-1** [comment] 2023-05-30 00:44
Try this: Open chocolate-doom.cfg and set `use_libsamplerate` to 1.

**Comment by QuartzSTQ** [comment] 2023-05-30 22:58
> Try this: Open chocolate-doom.cfg and set `use_libsamplerate` to 1.

That worked, and I notice that it's also enabled in Crispy Doom's configuration. Still strange that it defaulted to it being disabled for Chocolate Doom.

**Comment by ceski-1** [comment] 2023-05-31 02:51
`use_libsamplerate 0` uses SDL's resampler, which uses a Kaiser windowed sinc filter with good performance.

`use_libsamplerate 1` uses linear resampling which is the default for many source ports. The "crisp" sound is actually caused by aliasing artifacts, but I actually prefer it like you do.

Other values are documented [here](https://github.com/chocolate-doom/chocolate-doom/blob/e96d2c2c1bf33b3367cf40d234563d7c5465b614/src/m_config.c#L895-L908).

For comparison, the Sound Blaster 16 used a sinc filter for PCM (sound effects) and no filtering for OPL (music). Other 90's sound cards had various resampling methods.

So we see this quickly becomes a subjective topic. The default "muffled" audio in Chocolate Doom seems appropriate considering the popularity of Sound Blaster cards at the time of Doom's release. It's nice that there's an option to change it though.

**Comment by mfrancis95** [comment] 2023-10-01 22:23
Closing this because this has been resolved per https://github.com/chocolate-doom/chocolate-doom/issues/1310#issuecomment-1569420104

**Closed by mfrancis95** 2023-10-01 22:23 UTC
