### ISSUE TITLE
SFX volume depends on Music volume

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#625] opened 2015-10-14 06:34 UTC
I noticed this bug trying to turn off music to zero volume, and the game sounds disappeared too.
Sounds like that SFX volume gets multiplied by music volume, SFX volume being less or equal to music volume as a result (equal when SFX volume slider is at maximum).
The same bug can be found in Crispy Doom 3.0, as it's based on Chocolate Doom 2.2.

**Comment by haleyjd** [comment] 2015-10-16 21:16
Win32 native MIDI playback has had broken volume setting under all versions of Windows since Vista, same issue as the last several times this was reported. Solutions are to use OPL, timidity, or a hidef music pack.

**Comment by fragglet** [comment] 2015-10-16 21:29
Duplicate of #397 I think.

**Closed by fragglet** 2015-10-16 21:29 UTC
Labels: music, sfx, windows

**Comment by Zodomaniac** [comment] 2016-06-11 06:30
For some reason it works correctly now! :)
