### ISSUE TITLE
Changing the music volume affects Windoze Sound Mixer

### ISSUE THREAD

**Issue by tpoppins** [chocolate-doom/chocolate-doom#514] opened 2015-02-27 03:21 UTC
- WinXP SP3
- M-Audio Audiophile 96/24
- System MIDI default playback device - Microsoft GS Wavetable SW synth (default)
- General MIDI in Choco

After lowering music in Choco (almost, but not quite all the way down) I noticed music becomes inaudible in Prboom-plus. Turns out that using the Music Volume slider in Choco correspondingly affects Windoze' system mixer.

This doesn't happen in Prboom-plus which also uses SDL, so perhaps a fix could be imported from it.

**Comment by fragglet** [comment] 2015-02-27 04:20
Thanks for the report. This is a duplicate of #437.

**Closed by fragglet** 2015-02-27 04:20 UTC

**Comment by tpoppins** [comment] 2015-02-27 11:57
Hmm, I don't think these are the same issues. #437 is about SFX volume tied to music volume. Perhaps I should clarify: using the Music Volume slider in Choco correspondingly affects *the MIDI* slider in Windoze' system mixer. Or does this make no difference?

**Comment by AXDOOMER** [comment] 2015-02-27 12:35
It makes no difference. It's a limitation on the side of Windows, it supports MIDI very poorly.

**Comment by haleyjd** [comment] 2015-02-27 15:43
It actually *is* a separate issue, but there's likewise almost nothing that can be done about it. It is possible to open an MMSYSTEM handle at startup, play a "silent" MIDI, save the current MIDI volume level, and then at shutdown, repeat the process and reset the initial volume, but that's all 100% Win32-specific nonsense and is non-trivial to say the least.
