### ISSUE TITLE
Demo recorded from a savegame is played from the start of the level, not from the savegame.

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#839] opened 2017-01-14 08:41 UTC
I use command line -loadgame N -record demotest
Compared this to GZDoom that plays demos from savegames correctly.
Maybe fix this bug in Choco as well?

**Comment by fabiangreffrath** [comment] 2017-01-14 12:57
I didn't even know that it is at all possible to record demos from savegames, let alone play back demos from savegames. Would you mind providing us as savegame and a demo recorded starting from it?

**Comment by Zodomaniac** [comment] 2017-01-14 15:15
Here you are!
[play demo from savegame.zip](https://github.com/chocolate-doom/chocolate-doom/files/706015/play.demo.from.savegame.zip)

**Comment by linguica** [comment] 2017-01-14 16:33
IIRC, vanilla Doom doesn't support -loadgame and -record at the same time. (Not because it wasn't possible, but Carmack just didn't account for it.)

**Comment by AXDOOMER** [comment] 2017-01-14 21:35
It was only possible in earlier versions of Doom, I think v1.2 was able to do that.

**Comment by CapnClever** [comment] 2017-01-14 21:55
The intended parameter to record from a savegame was [`-recordfrom`](https://doomwiki.org/wiki/Parameter#-recordfrom): it never worked, though you can unsuccessfully attempt to use it in Heretic/Hexen since those were based on 1.2 Doom.

This seems feasible to implement as extended demo functionality: I don't foresee synchronization problems, since the saved game holds a valid gamestate from which to start. Definitely would wrap it in `-strictdemos`.

Is there a want for it? I myself have spent a good deal of time adding recording features and I'm struggling to consider common use cases. It requires that you keep the demo file and the save file around, and to pass both of those around when sharing it. Since it's an extension of functionality rather than emulation, some justification other than "it's broken" will provide motivation to implement.

**Comment by AXDOOMER** [comment] 2017-01-14 22:01
There no need for this. Implementing it in Chocolate-Doom would make it the only port that supports this, demos would be unplayable anywhere else and it's not vanilla.

**Comment by fragglet** [comment] 2017-01-14 22:33
Is it possible to use `-loadgame` with `-playdemo` in Vanilla Doom?

**Comment by Zodomaniac** [comment] 2017-01-15 07:38
> Implementing it in Chocolate-Doom would make it the only port that supports this, demos would be unplayable anywhere else and it's not vanilla.
GZDoom can record/play demos from savegames, but it has a totally different demo format.
Why not record deoms from savegames in Choco and Choco-based ports like Crispy?

**Comment by CapnClever** [comment] 2017-01-15 19:59
Implementation via another port, especially a non-vanilla one, isn't justification to do the same in this port. The important question is "who benefits from this feature" and, as I previously mentioned, I'm finding it hard to suggest a use case. I suppose you might have a situation where you want to record a specific demo without having to start from scratch every time, but the necessary sharing of the savegame seems to outweigh that convenience factor. Prboom-plus has the `-recordfromto` parameter that allows you to continue from the end of an existing demo, providing the means to stitch things together and avoiding the need to perform everything in a single run.

Why is it desirable for specifically Chocolate Doom to be able to do record from a savegame?

**Comment by fabiangreffrath** [comment] 2017-01-15 20:16
@Zodomaniac I might have a look into implementing this in Crispy. Would you mind filing a request ticket over at the Crispy tracker, please (I tend to forget these things if they aren't properly documented somewhere)?

**Comment by AXDOOMER** [comment] 2017-01-16 23:55
> The important question is "who benefits from this feature" and, as I previously mentioned, I'm finding it hard to suggest a use case. 

Even if a feature would bring a lot of benefits and would be very useful, the feature request may be declined. That's what happen every time there is a _Doom-plus limits_ feature request.

**Comment by Zodomaniac** [comment] 2017-01-17 08:34
> Even if a feature would bring a lot of benefits and would be very useful, the feature request may be declined. That's what happen every time there is a Doom-plus limits feature request.

There is Crispy Doom for thse who want Choco with Doom-Plus features :)
and I was asking to fix a bug that has no reason to be maintained IMO, not implement a feature.
Anyway, this is fixed in Crispy now, thanks Fabian! :1st_place_medal: 
https://github.com/fabiangreffrath/crispy-doom/commit/f7401a24b554b18528f78c2312d28a1d0de6bae6

**Comment by Zodomaniac** [comment] 2017-01-17 13:20
Here you can see why I wanted this fixed!
I found this WAD, Infested Outpost, on ModDB and discovered that its metal soundtrack was the same BPM as... no spoilers, just extract the archive ​
https://drive.google.com/file/d/0Bycv-h0BCyw0RWlWUUdINXRjNTg
and launch PLAYDEMO.BAT inside!
Enjoy!

Now Crispy Doom does record and play back demos from savegames, but I thought this fix would be even better in Choco to be inherited by other Choco-based ports.

**Comment by fabiangreffrath** [comment] 2017-01-17 14:09
By its very concept, Choco tries to resemble Vanilla as closely as possible. If a feature doesn't work in a specific way in Vanilla, then there is no room for it on Choco either. No matter how neat or useful it might be.

Now that this has been fixed downstream, I guess we may close this request?

**Closed by fabiangreffrath** 2017-01-17 14:09 UTC

**Comment by fragglet** [comment] 2017-01-17 14:20
> then there is no room for it on Choco either. No matter how neat or useful it might be.

That's not strictly true, particularly in the case of demos. We've expanded support for those quite a bit and we have a specific exception in PHILOSOPHY for them now. However, I do think that the record-from-savegame case is a bit too niche to bother with.

**Comment by AXDOOMER** [comment] 2017-01-17 17:49
>  I was asking to fix a bug that has no reason to be maintained IMO, not implement a feature.

It's not a bug, vanilla was never meant to do this and it was never coded into vanilla's original source code. Crispy Doom is not vanilla, so features that you'd never find in Chocolate-Doom or a hacked Doom executable are accepted there.
