### ISSUE TITLE
GUS pseudo-emulation is awful with some patches

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#878] opened 2017-03-04 23:12 UTC
Chocolate-Doom's emulation may be fine with the EAWPATS GUS patches and the GUS401 patches (distributed as dgguspat.zip on idgames), but it's broken with the PPL160 patches. (I didn't test with other patches, these are the one that I always use with DOSBox because others suck, so the problem may affect other sets of patches)

This affects both Doom 1 and Doom 2, but Doom 2 seems to be affected more (maybe because of changes to the DMXGUS lump). Map01's music sounds like if it was on the Jaguar 32X. 

If you don't have the PPL160 patches, grab them here: 
http://www.mediafire.com/file/8mezjdsyuj3/GUS+Install.7z

**Comment by seascape** [comment] 2017-07-03 22:13
I ended up here to see if I'd done something wrong with my GUS patch folder. Though I've never heard a real-life GUS, the (final official) 4.11 patch set doesn't sound so hot to my ears, with too many wrong-sounding instruments (Doom 2 MAP01 is especially awful, and the little tooting flute in E1M2...).

Unfortunately any patch set higher than 4.11 just sounds busted, with tons of static. So for Chocolate Doom it's currently 4.11 or nothing, as far as I can tell. Looking for a non-GUS ChocoDoom music solution until/unless GUS quality improves.

Results were identical in 3.0 beta.

**Comment by fragglet** [comment] 2017-07-06 10:20
> too many wrong-sounding instruments (Doom 2 MAP01 is especially awful, and the little tooting flute in E1M2...).

This is a bug in Vanilla Doom that Chocolate Doom is simply faithfully emulating. If you want to play with the correct instruments, here's what to do:

1. Download [dgguspat.zip](https://www.doomworld.com/idgames/music/dgguspat) from idgames and unzip.

2. dgguspat.zip contains the GUS patch files (which you already have) but also includes `timidity.cfg` - this is the important thing you need.

3. Open chocolate-setup, go to the Sound Configuration dialog. Choose "Native MIDI" as a music type. Set "Timidity configuration file" to point to the timidity.cfg file where you've extracted dgguspat.zip.

**Comment by seascape** [comment] 2017-07-06 22:26
Thanks for the reply.

That's actually the configuration I switched to, and it sounds good, but I was confused by it being called Native MIDI (thought that implied system-level MIDI driver). So if I understand, Native MIDI / timidity.cfg sounds like what a GUS *could* sound like in vanilla Doom, if it was not affected by the bug?

That said, the post-4.11 patch sets still sound broken w/ the Native MIDI / timidity.cfg setup. Here is a quick recording from Doom 2 map01:
[cd2 gus 161.zip](https://github.com/chocolate-doom/chocolate-doom/files/1129436/cd2.gus.161.zip)

Is this known/expected too?

**Comment by AXDOOMER** [comment] 2017-07-06 23:30
I wanted to test dgguspat with the Timidity configuration file and Native MIDI on Debian 9 (my only system right now), but somehow it doesn't work because it uses my system's sound font for Native MIDI and GUS (emulated) defaults to Native MIDI. I have specified the path to the patches and have made sure the letters are in the correct case. 

I wonder what could be wrong. The package `timidity` is installed. Chocolate-Doom is version 2.3.0.

**Comment by AXDOOMER** [comment] 2017-07-06 23:54
> That said, the post-4.11 patch sets still sound broken w/ the Native MIDI / timidity.cfg setup. Here is a quick recording from Choco 2.30 / Doom 2 map01 / 1.61 Pro Patches Lite:
cd2 gus 161.zip
> Is this known/expected too?

This is the bug that I am reporting. Your recording shows exactly how it is, but since I have checked on the Chocolate-Doom wiki, I have read that SDL_mixer uses Timidity and thus the bug may come from there.

**Comment by fragglet** [comment] 2017-10-22 23:18
Closing issue since I think we established that this is intended behavior.

**Closed by fragglet** 2017-10-22 23:18 UTC
Labels: accuracy, music

**Comment by AXDOOMER** [comment] 2017-10-23 00:38
>> too many wrong-sounding instruments (Doom 2 MAP01 is especially awful, and the little tooting flute in E1M2...).

> This is a bug in Vanilla Doom that Chocolate Doom is simply faithfully emulating. If you want to play with the correct instruments, here's what to do


Does that mean that DOSBox is not faithful emulating GUS?
