### ISSUE TITLE
Introduce a network protocol version

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#686] opened 2016-03-24 19:36 UTC
Hi there,

I think, Choco's network protocol hasn't changed for ages. However, both client and server still send the entire PACKAGE_STRING, i.e. program name and version, when establishing a connection. This means that it is impossible (or at least complicated) to connect a, say, Choco 2.2 client to a Choco 2.2.1 server, although the network protocol hasn't changed at all.

Needless to say, it requires network-compatible forks to maintain another variable to keep track of the latest Choco version that they are compatible with (_hint_).

Let's just say, the network protocol as it is now is version 1 and any future revisions to this protocol result in raising this number. This way, we could make the protocol independent of the game version and even of the engine's name.

Cheers,

Fabian

**Comment by fragglet** [comment] 2016-03-24 20:16
Note that it isn't just the network protocol that is important: it's also the game behavior. This can be triggered by something really subtle: for example, suppose that Chocolate Doom 7.8.1 fixes a bug that was present in Chocolate Doom 7.8.0 where some particular vanilla behavior was not emulated quite right. If that behavior is triggered in-game, two clients on those particular point releases could desync.

That said, the philosophy of the project pretty much guarantees that there are not going to be a significant compatibility-breaking changes like these; when they do occur, it's most likely they'll be to subtle things that are very unlikely to trigger a desync in practice. So the above explanation is really just an explanation of why the version checks are so strict; when I implemented the networking I erred on the side of caution and made them overly strict.

So as you suggest, I think we should change the protocol (Chocolate Doom v3 is a good opportunity to do this). I'm not sure what the replacement version identifier should exactly look like but I would like to explicitly support network-compatible forks like Crispy Doom in the scheme. Furthermore: I'd like to support a *hierarchy* of forks; for example, suppose someone forks Crispy Doom and creates a fork that is somehow compatible with Crispy Doom but not Chocolate Doom? (slightly contrived example but I hope you get the idea).

**Comment by chungy** [comment] 2016-03-24 22:37
> Note that it isn't just the network protocol that is important: it's also the game behavior. This can be triggered by something really subtle: for example, suppose that Chocolate Doom 7.8.1 fixes a bug that was present in Chocolate Doom 7.8.0 where some particular vanilla behavior was not emulated quite right. If that behavior is triggered in-game, two clients on those particular point releases could desync.

The intention I had with the stable branches was that they would always be network compatible. I learned the hard way that it wasn't possible in the current system, when the version was raised to 2.2.1. If this strictness didn't exist, they would be compatible. In fairly fuzzy terms, cherry-picking commits for a stable release is a judgment call about whether it would break anything compared to the prior releases in that series.

An incrementing integer for the protocol version would come in handy, and while in my mind, it would be nice that it gets updated each time a breaking change happens anywhere, guaranteeing a compatibility between random Git snapshots, it would be too easy to forget and maintain. Realistically, it ought to just be updated alongside the regular major version bump. Chocolate Doom 3.0.0 -> protocol 1, Chocolate Doom 3.1.0 -> protocol 2, etc.

> Furthermore: I'd like to support a hierarchy of forks; for example, suppose someone forks Crispy Doom and creates a fork that is somehow compatible with Crispy Doom but not Chocolate Doom? (slightly contrived example but I hope you get the idea).

Too contrived and over-engineered, in my opinion. If somebody wants to make a compatible fork, it should treat Chocolate Doom as the ultimate upstream, and any breaks would be created by bugs in either Crispy Doom or said hypothetical fork.

Even more contrived: imagine that a port not directly related to our own code base tries to gain network-compatibility with Chocolate (this might not be entirely far-fetched for PrBoom-Plus and Odamex, mind you). They can introduce bugs of their own and no sort of hierarchy is going to help the scenario.

**Comment by Danfun64** [comment] 2016-03-27 23:28
I think PrBoom-Plus is more likely than Odamex. PrBoom-Plus has pretty bad netcode atm afaik. Odamex, being a zdoom 1.22 based C/S port, is far less likely to implement Chocolate style multiplayer...
...
maybe Eternity would.

**Comment by XCOPY-** [comment] 2016-04-02 22:29
This seems to be a duplicate of #685, in a way. If Chocolate-Doom decides to become network compatible with vanilla Doom (via Dosbox), such versioning becomes pointless.

**Comment by jmtd** [comment] 2016-04-04 08:47
> This seems to be a duplicate of #685, in a way. If Chocolate-Doom decides to become network compatible with vanilla Doom (via Dosbox), such meta data becomes pointless.

Not really. It depends how #685 is addressed, but I don't see TCP/IP support going away, and it could be useful for that alone.

**Comment by fragglet** [comment] 2016-04-04 14:46
The two bugs are completely unrelated.

**Comment by fabiangreffrath** [comment] 2017-09-25 09:33
> I think we should change the protocol (Chocolate Doom v3 is a good opportunity to do this)

So maybe now is the right time to get this discussion on track again: Let's please introduce a "network compatibility indication string" that can be shared among Choco releases and also forks to indicate network compatibility in time for the upcoming SDL2-based 3.0 release!

**Comment by fragglet** [comment] 2017-09-25 14:53
Completely agree. I'm adding this as a blocker for v3.

**Comment by jmtd** [comment] 2017-09-27 13:38
If you guys think you can get this done before the anniversary of the last release, I will reluctantly concur it's a good idea to get it done in the major version release. But I really, really hope we can get v3 out this calendar year!

**Closed** 2017-10-01 06:19 UTC
Labels: network

**Comment by fragglet** [comment] 2017-10-08 22:36
So just a quick note - #943 fixed this bug, and as of 7a611a627d389d5 I've also added the protocol list to query responses, so incompatible servers will be ignored in the setup tool.
