### ISSUE TITLE
Chocolate Strife - Enemies can't be gibbed

### ISSUE THREAD

**Issue by GeoffLedak** [chocolate-doom/chocolate-doom#645] opened 2015-12-07 05:33 UTC
I was just testing Chocolate Strife v2.2.1 on Windows and noticed that acolytes and NPCs are no longer being gibbed (splattered?) when in close proximity to grenades or other explosive weapons. They always show their regular death animation regardless of the strength of the hit that killed them.

**Comment by fragglet** [comment] 2015-12-26 07:48
@haleyjd - any thoughts?

**Comment by haleyjd** [comment] 2016-01-05 21:49
@fragglet Have you repro'd this? There was no problem with gibbing in the codebase as of SVE development. I am currently occupied on Turok EX dev.

**Comment by fragglet** [comment] 2016-01-05 22:12
Just checked and it does indeed appear to be the case.

Testing with grenades the Acolytes never gib. In p_inter.c/P_KillMobj we find this code:

            if(target->health < -target->info->spawnhealth 
                && target->info->xdeathstate)
                P_SetMobjState(target, target->info->xdeathstate);
            else
                P_SetMobjState(target, target->info->deathstate);

Further down in P_DamageMobj we find this:

        // villsa [STRIFE] grenades hurt... OUCH
        if(inflictor && inflictor->type == MT_HEGRENADE)
            target->health = -target->info->spawnhealth;

It looks like this is intended to trigger the gib code above, but since it uses < instead of <= it is not triggered. Any chance you can have a quick look at the disassembly and figure out which it is supposed to be?

**Comment by chungy** [comment] 2016-01-06 01:29
It looks like that particular part was changed in Veteran Edition: https://github.com/svkaiser/strife-ve/blob/master/strife-ve-src/src/strife/p_inter.c#L1184

Given that SVE didn't have such a strict adherence to vanilla accuracy, it might not be wise to just copy from it, but I wouldn't be surprised if either Kaiser or Quasar fixed gibbing in it and forgot about that.

**Comment by haleyjd** [comment] 2016-01-10 02:18
The SVE code is irrelevant, although it unknowingly fixes a problem in the original game. I have confirmed the assembly code of both functions. The gib health check in P_KillMobj is exactly the same as it was in vanilla Doom. The code in P_DamageMobj sets mo->health to -mo->info->spawnhealth, apparently believing this ought to trigger the gib state when in fact it prevents it.

When I asked earlier if this was repro'd, I sort of meant if anybody had verified it against the DOS version as well as checking Choco, since verifying DOS behavior is an important part of this project. As far as I can tell, this is a bug that should exist in the original game. If it doesn't then some other piece is missing here.

**Comment by haleyjd** [comment] 2016-01-11 08:45
I am drawing a blank on this. Going over all the involved functions, the assembly would seem to indicate that Choco's behavior is normal, but neither the 1.2 nor 1.31 EXEs demonstrate the same behavior. Something's odd.

**Comment by haleyjd** [comment] 2016-01-11 10:11
Fixed in 37c1162

**Closed by haleyjd** 2016-01-11 10:11 UTC
Labels: confirmed, Strife
