### ISSUE TITLE
Support for SC-55 FLAC soundtracks

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#245] opened 2013-12-08 19:54 UTC
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/245/) on Sourceforge by [twipley](https://sourceforge.net/u/twipley/profile/), 2012-08-23 12:24:48:

http://www.doomworld.com/vb/showthread.php?postid=1099612\#post1099612

The intended method for listening to Doom music is through a Roland SC-55 (Sound Canvas) piece of hardware.

In modern times, it is burdensome for such a card to be carried in a system, so the best thing to do would be to import high-fidelity recordings of the music to disk. Once FLAC music that way is stored there, one is to remove the SC-55 device from the system, and to use the imported files as accurate music output for the game.

However, the current Chocolate-Doom engine does not, not even from the command line, provide for any means for this intended music to be played out as a replacement for the supported MIDI-music playback.

The issue lies in the variance between the fact that MIDI playback through mere software VSC-55 does not do justice to the original game, and the one that the philosophy of the project is to, in the long-run, achieve maintenance of the original Doom experience in modern times.

**Comment by twipley** [comment] 2015-04-30 10:06
Hey there! a few questions about this:

1) are the d_bunny, d_inter, d_intro, and d_victor tracks looping or supposed to loop? what is the correct/intended behaviour?

2) i am noticing a few holes there. https://github.com/chocolate-doom/music-packs/blob/master/doom1-music.cfg -- or rather, a few inconsistencies. blume to take him as a reference, chooses d_e2m9 over d_e3m1 for the file naming. here is a file list http://i.imgur.com/1qz9nlz.png -- could that be used as a standard?

3) i have no checksum match for those doom1-music.cfg -- using either boosted or raw versions. it is getting me curious.

**Comment by fragglet** [comment] 2015-04-30 15:10
1a) I don't think these are supposed to loop, except d_inter.
1b) Shouldn't make a difference as although they're the same audible song they're different lumps in the WAD
2) Maybe. The music-packs files are (currently) just an example of some good configurations. They're not designed for use with any particular set of recorded music. As mentioned in this bug, there are a couple of different such recordings. I'd be happy to standardize on a particular naming scheme though.
3) I don't understand. What checksum?

**Comment by twipley** [comment] 2015-04-30 22:21
here are my tries at it:
http://kopasite.net/up/0/raw_doom1-music.cfg
http://kopasite.net/up/0/boosted_doom1-music.cfg

for these two (blume-encoded) packs:
http://sc55.duke4.net/flac/doom_sc55_flac.zip
http://sc55.duke4.net/flac/doom_sc55_flac_raw.zip

The file-naming system I am proposing is one that follows an alphanumeric logic: the second and later occurrences are simply left out both in the music folder and in the related cfg file, and it is always the first occurrence (e.g., d_e2m9 rather than e3m1) that is to be called by Chocolate Doom. This is the system Blume uses as the duplicates he tells, are unneeded because his are just copies of the same base files.

**Comment by twipley** [comment] 2015-04-30 22:49
I wonder if, in Windows, line endings should be set to "Windows" and the slashes in the cfg files be backwards (e.g., \) instead of forwards.

In any case, I'll stay tuned and will test those when compatibility with x86 XP systems or such is achieved. To not hesitate to drop a line here if you need beta testing on the indev master branch!

**Comment by fragglet** [comment] 2015-04-30 23:51
> The file-naming system I am proposing is one that follows an alphanumeric logic: the second and later occurrences are simply left out both in the music folder and in the related cfg file, and it is always the first occurrence (e.g., d_e2m9 rather than e3m1) that is to be called by Chocolate Doom. This is the system Blume uses as the duplicates he tells, are unneeded because his are just copies of the same base files.

Sure, seems like a logical enough system.

> I wonder if, in Windows, line endings should be set to "Windows" and the slashes in the cfg files be backwards (e.g., ) instead of forwards.

Better to use Unix format and forward slashes for portability.

**Comment by twipley** [comment] 2015-05-01 00:02
Ok nice, for reference that's what the above cfg files for music were set to.

**Comment by chungy** [comment] 2015-05-01 10:14
> 3) just as a footnote; not really a question: i have no checksum match for those doom1-music.cfg -- using either boosted or raw versions. it is getting me curious.

It looks like you're trying to match the SHA-1 of your FLAC files rather than the SHA-1 of the music lumps within the WAD. Use `chocolate-doom -iwad doom.wad -dumpsubstconfig doom1-music.cfg` (for example) to generate the initial file, then add in your file paths (with forward slashes) without modifying the SHA-1.

**Comment by twipley** [comment] 2015-05-01 16:04
I really am having problems doing things under Linux, so I'll wait for the Windows version to test this.

It seems some (https://github.com/chocolate-doom/chocolate-doom/issues/428) have already got it working under Windows. So it's a big hope for us under x86 XP (or such systems).

**Comment by twipley** [comment] 2015-05-01 18:19
here is another try at it:
http://kopasite.net/up/0/doom1-music.cfg

each lump should find its way to the appropriate flac file.

there are 23 flac files, plus this cfg file, to be put in the music folder.

feedback would be appreciated!

footnote:

Blume said somewhere he could generate the below files using his tools and expertise, but as plume states it (cf. http://www.doomworld.com/vb/post/1284152), audible differences seem just for three out of those five, and are quite trivial so publishing extra audio files might well not be worth the trouble.

36b14bf165b3fdd3958ee83e4929063f051ada2f = d_e3m5.flac
e77c3d42f2ea87f046074bd4e3ff1e535da1c653 = d_e3m6.flac
3d85ec9c10b5ea46556899cfba701a556e27ca34 = d_e3m7.flac
4d42e2ce1c1ff192500e7a08e72c85fe59741487 = d_e3m9.flac
b2e05b4e8dff8d76f8f4c3a724e7dbd365390536 = d_inter.flac

**Comment by twipley** [comment] 2015-05-07 14:45
1) I've just tested under Linux, and it doesn't work for me using the file I provided. Is it something on my end?

2) Out of curiosity, is it possible to use absolute paths in that config file?

**Comment by SpiralBrad** [comment] 2015-05-25 00:59
It seems the music loading works on windows builds of Chocolate Doom 2.1.0 using the set of DLLs from [Crispy Doom 2.3](http://www.chocolate-doom.org/wiki/index.php/Crispy_Doom#Binaries).

Standard things apply; set up the music .cfgs with correct paths, select Native MIDI for the music device.

**Comment by twipley** [comment] 2015-05-25 17:48
Good to know!

plume said he got it working too, but IIRC, by going at the source: http://downloads.xiph.org/releases/flac/flac-1.3.1-win.zip

**Comment by Danfun64** [comment] 2016-04-08 16:47
On my (Xubuntu 15.10 x86_64) system, when some flacs loop, this is a bit of studder for some reason.

**Comment by haleyjd** [comment] 2016-04-08 18:13
SDL(2)_mixer sometimes have issues keeping the music buffer full because it doesn't read far enough ahead. I've had this problem on my own PC in Strife:VE, Noctropolis, and Turok EX, if something else is doing a lot of disk reads or using tons of CPU (typically this turns out to be Firefox and/or Flash).

**Comment by twipley** [comment] 2016-04-15 14:45
It would be much welcome to receive an official statement regarding this under Windows.

In other words, is an official way to make this work (under Windows) planned (to be programmed), or does the author (fraggle) endorse one method or the other from those which were posted (here) back in the end of may (2015)? Are both equivalent in operation and sufficient in value?

**Comment by fragglet** [comment] 2016-04-15 15:44
I'm not sure exactly what you want a statement on, but if the question is about when music packs will be officially supported on Windows, the answer is that the DLLs will be packaged with the 3.0 release (SDL2 port). See my email here from a few months ago:

https://groups.google.com/a/soulsphere.org/forum/#!topic/chocolate-doom-dev-list/tfr-FKhfBKU

**Comment by twipley** [comment] 2016-04-30 16:54
Thanks for the quick answer.

Would it be possible to know, will these be the same DLLs as the ones from the FLAC website or from the Crispy Doom project?

**Comment by fragglet** [comment] 2017-01-27 21:57
Late answer but we're building our DLLs from source. You can check out the sdl2-branch betas at http://latest.chocolate-doom.org which include them.

I'm closing this bug as I think it's now complete. Digital music packs will be in the 3.0 release.

**Closed by fragglet** 2017-01-27 21:57 UTC
Labels: music
