### ISSUE TITLE
[Setup] ESC key binding

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#850] opened 2017-02-02 06:54 UTC
Tested on: Chocolate Doom 2.3.0 and SDL2 (02/01/2017), Crispy Doom 3.5.
Additionally tested on Linux, it does not seems to be OS-specific bug, but libtextsreen logic.

ESC key can not be (re)binded, because pressing this key simply closes dialogue window.
It is critical only if accidentally unbind "Activate menu" and then save configuration. It this case, there is will no be way back to bind ESC key, and only deleting of .cfg files can help.

Suggestion: it might be a good idea if menu will be always activating (i.e. hardcoded) by pressing ESC, and additionally by pressing button, binded in setup executable.

**Comment by chungy** [comment] 2017-02-02 14:44
Deleting just the `key_menu_activate` line or setting it to 1 in `chocolate-doom.cfg` could be a workaround alternative to deleting the whole file.

**Comment by fragglet** [comment] 2017-02-02 15:15
Duplicate of #353 (and see past discussion there), but thanks for the report nonetheless.

**Closed by fragglet** 2017-02-02 15:15 UTC
Labels: setup
