### ISSUE TITLE
fullscreen_width and fullscreen_height variables don't work

### ISSUE THREAD

**Issue by SoDOOManiac** [chocolate-doom/chocolate-doom#1010] opened 2018-03-31 07:11 UTC
### Background

Version of Chocolate Doom: Git 31.03.2018

Operating System and version: Windows 7

Game: (Doom/Heretic/Hexen/Strife/other) All

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: The entire screen is used instead of the specified part.

Expected behavior: I set the `fullscreen_width` to 1728 and `fullscreen_height` to 1080 and expected the game to be rendered fullscreen with black bars on the sides, like this:
![16-10 spherical powerup_with_bb](https://user-images.githubusercontent.com/15119473/38160789-976871d6-34cb-11e8-92a8-de491f7de6f0.png)
(the screen is from Crispy Doom but in Choco the situation is the same)

**Comment by fabiangreffrath** [comment] 2018-03-31 08:32
Do you have aspect ratio correction enabled or not?

**Comment by Zodomaniac** [comment] 2018-03-31 09:46
No, I dont, naturally. If I did it would be 4:3. with black bars.

**Comment by fragglet** [comment] 2018-04-01 05:41
This is working as intended, as covered in #968.

**Comment by fragglet** [comment] 2018-04-01 06:18
Correction: I think it perhaps isn't.

If you've set `fullscreen_width` / `fullscreen_height` to 1728x1080 then it should render to that exact size. It sounds like it's adjusting to 1920x1080 and then using the whole screen.

**Comment by chungy** [comment] 2018-04-01 07:47
Don't those variables set the monitor resolution directly? 1728x1080 is unlikely to ever be a valid mode, except perhaps in a virtual machine.

**Comment by fragglet** [comment] 2018-04-01 18:48
The SDL behavior used to be that if you specified a nonexistent mode, it would set the next highest mode and give you a windowbox inside it. So I thought that configuring 1728x1080 would get the appropriate result, but I guess not - maybe it's changed with SDL2.

**Comment by linguica** [comment] 2018-04-04 03:11
For what it's worth, I tried on Mac and as far as I could tell, the output actually had letterboxes on it like  @Zodomaniac was looking for, but it seems to me that it *should* have rendered completely fullscreen at 16:9 instead of a letterboxed 16:10.

I almost wonder if `aspect_ratio_correct` is too simplistic of a variable, and if it should be replaced by a `par_width` and `par_height` (`par` meaning pixel aspect ratio) that define the exact dimensions of each game pixel on the canvas. The default values would be `par_width 5` and `par_height 6`, which would exactly describe the pixel aspect ratio as shown on a "normal" monitor. you could change it to `par_width 1` and `par_height 1` to change to "squished" mode which some people seem to want. And you could even change it to some bizarre arbitrary ratio if, for instance, you were trying to run Doom on some custom screen with an unusual aspect ratio.

**Comment by fabiangreffrath** [comment] 2018-04-04 06:26
> should be replaced by a par_width and par_height

We could also replace `aspect_ratio_correct` by a float variable that directly defines the aspect ratio, e.g. `1.2` for the corrected one or `1.0` for square pixels.

**Comment by Zodomaniac** [comment] 2018-04-04 09:32
@fabiangreffrath 
>We could also replace `aspect_ratio_correct` by a float variable that directly defines the aspect ratio, e.g. `1.2` for the corrected one or `1.0` for square pixels.

Directly defines the AR correction factor, I guess you mean)

**Comment by Zodomaniac** [comment] 2018-04-18 10:46
Reported the SDL bug https://bugzilla.libsdl.org/show_bug.cgi?id=4140

**Comment by Zodomaniac** [comment] 2018-04-19 08:05
Is this bug present in other OSs than Win7?

**Comment by Zodomaniac** [comment] 2018-06-08 14:00
What a surprise! In StasBFG's Crispy build http://doomgod.com/ports/crdoom5.7z, i.e. with SDL_DLLs compiled in Visual Studio the fullscreen_width and fullscreen_height variables work, the screen size is 1728x1080 letterboxed on the sides!

**Comment by chungy** [comment] 2018-06-09 03:35
> with SDL_DLLs compiled in Visual Studio the fullscreen_width and fullscreen_height variables work, the screen size is 1728x1080 letterboxed on the sides!

I was looking through `SDL_video.c` in both 1.2 and 2.0 and I believe that all the code to support the functionality was actually removed in 2.x. Is there source code available for the build in that 7z archive?

**Comment by Zodomaniac** [comment] 2018-06-09 06:48
@chungy There is no code in that archive, only Crispy and Setup EXEs and SDL DLLs of 2.0.5 version.
I asked the build author to provide the code.

**Comment by chungy** [comment] 2018-06-09 08:28
Ah. That's before the unrestricted aspect code was merged.

**Comment by fabiangreffrath** [comment] 2023-11-29 07:34
Just got comfirmation from upstream that this is not considered a bug:

`This is expected, you can request a fullscreen mode, but you must either check to see what is actually available or use SDL_RenderSetLogicalSize() to set a logical size for your content.`

https://github.com/libsdl-org/SDL/issues/2873#issuecomment-1823140583

**Closed by fabiangreffrath** 2023-11-29 07:34 UTC
Labels: graphics
