### ISSUE TITLE
1 byte boolean

### ISSUE THREAD

**Issue by floppes** [chocolate-doom/chocolate-doom#509] opened 2015-02-19 08:22 UTC
I've ported Chocolate Doom to an ARM Cortex-M4 microcontroller using the GCC maintained by ARM (https://launchpad.net/gcc-arm-embedded). With default compiler options, enums are as small as possible. In the definition of boolean in doomtype.h this results in boolean to be 8 bits wide:

```
typedef enum 
{
    false, 
    true
} boolean;
```

This causes errors in st_stuff.c line 1267 when STlib_initMultIcon is called and a boolean is casted to int*. When accessing st_multicon_t.inum later in STlib_updateMultIcon, it reads the additional 3 bytes in memory around the boolean and interprets them as belonging to inum. When picking up a new weapon the result was a freeze because the patch that displays which weapons you own was drawn at coordinates way off the screen.

My workaround is a change of the boolean definition to force it to be 32 bits wide:

```
typedef enum 
{
    false	= 0,
    true	= 1,
    undef	= 0xFFFFFFFF
} boolean;
```

The code in st_stuff.c:1267 also assumes that true is 1, where some compilers define true to be !0 which could be 0xFF or 0xFFFFFFFF or any other value except 0.

**Comment by fabiangreffrath** [comment] 2015-02-19 14:45
Hm, what if we change the type of player_t.weaponowned from boolean to int in doom/d_player.h?

**Comment by haleyjd** [comment] 2015-02-19 15:25
That's bad practice. Boolean is a semantic type and should not simply be discarded. If anything, I'd suggest changing boolean to be a typedef of int32_t so that it is always the same size as it was under Watcom, and then keeping the enum either untyped or with a different name.

By the way, Eternity ran into this same issue when I changed boolean into C++ bool. This was the *only* place left in our code using booleans as if they might be 32-bit integers.

**Comment by fragglet** [comment] 2015-02-19 16:07
That (int *) cast looks like a really bad false assumption:

https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/st_stuff.c#L1267

We should fix assumptions like this rather than hacking the boolean type to force it to be int-sized.

I'd be surprised if there isn't other code in there that relies on this assumption as well. Ideally we should find some way to reproduce the bug on a desktop machine and then run the statcheck tests to see if we can find similar bugs.

Testing Heretic/Hexen/Strife is another matter :(

**Comment by sneakernets** [comment] 2015-02-19 16:26
I *just* had to do this recently with all `int*` casts when porting Oblige to OS X. Changing `boolean` has led to headaches in the Doom Retro project, so @fragglet 's proposal may be the best route when it comes to portability.

**Comment by haleyjd** [comment] 2015-02-19 16:47
Please then be prepared to audit the code of all four games for similar issues. Fixing just this one and dusting off your hands afterward will just leave us to run into the same problems again and again in the future. My suggestion was one which would just take care of the problem with minimal impact on the rest of the codebase, which doesn't care how boolean is defined so long as it's defined.

**Comment by camgunz** [comment] 2015-02-19 18:18
I argue for a hybrid approach.  Rename `boolean` to `dboolean` (like lots of other ports, which is maybe sacrilege), and typedef `dboolean` to `int32_t`, as @haleyjd suggested.  Then only use `dboolean` where the code needs 4-byte booleans, and use `bool` (or whatever) everywhere else.  It serves as documentation that the code semantically uses booleans, but technically treats them as `int`s.

**Comment by fragglet** [comment] 2015-02-19 19:30
I really don't want to complicate the code by adding a second boolean type. It shouldn't be necessary.

As I see it, it should be relatively straightforward to use gcc's type checking to do an audit that is mostly "good enough":

1. Change boolean to be a typedef char (temporarily, never committed!), like the ARM cortex example. Check compiler warnings carefully - any mismatches should now be detected and flagged.

2. The only remaining problems should be caused by static casts, as with the example you've uncovered here. So we need to do a regex search of the codebase for int and boolean casts. Shouldn't be hard with egrep.

3. With the typedef still in place, run through the statcheck tests.

I think that should get us at least 95% of the way there. It's remotely possible there might be issues caused by void pointers that get missed.

Another option might be to actually commit the typedef char change and have the next release work that way. It might help shake out any remaining bugs, particularly in the Heretic/Hexen/Strife code.

**Comment by fragglet** [comment] 2015-02-19 19:48
Here, I did (1) and these are the new warnings that appeared. They're all resulting from assigning to booleans from integer values (they need != 0 added):

```
doom:

p_inter.c: In function ‘P_TouchSpecialThing’:
p_inter.c:606:56: warning: overflow in implicit constant conversion [-Woverflow]
  if (!P_GiveWeapon (player, wp_chaingun, special->flags&MF_DROPPED) )
                                                        ^
p_inter.c:634:55: warning: overflow in implicit constant conversion [-Woverflow]
  if (!P_GiveWeapon (player, wp_shotgun, special->flags&MF_DROPPED ) )
                                                       ^
p_inter.c:641:60: warning: overflow in implicit constant conversion [-Woverflow]
  if (!P_GiveWeapon (player, wp_supershotgun, special->flags&MF_DROPPED ) )
                                                            ^

hexen:

p_spec.c: In function ‘P_ActivateLine’:
p_spec.c:867:26: warning: overflow in implicit constant conversion [-Woverflow]
     repeat = line->flags & ML_REPEAT_SPECIAL;
                          ^

strife:

p_enemy.c: In function ‘A_Look’:
p_enemy.c:894:48: warning: overflow in implicit constant conversion [-Woverflow]
     if (!P_LookForPlayers (actor, actor->flags & MF_GIVEQUEST) )
                                                ^
p_enemy.c: In function ‘A_FriendLook’:
p_enemy.c:978:53: warning: overflow in implicit constant conversion [-Woverflow]
             if(P_LookForPlayers(actor, actor->flags & MF_GIVEQUEST))
                                                     ^
p_inter.c: In function ‘P_TouchSpecialThing’:
p_inter.c:540:59: warning: overflow in implicit constant conversion [-Woverflow]
         if(!P_GiveWeapon(player, wp_rifle, special->flags & MF_DROPPED))
                                                           ^
p_inter.c:563:63: warning: overflow in implicit constant conversion [-Woverflow]
         if(!P_GiveWeapon(player, wp_hegrenade, special->flags & MF_DROPPED))
                                                               ^
p_inter.c:577:61: warning: overflow in implicit constant conversion [-Woverflow]
         if(!P_GiveWeapon(player, wp_elecbow, special->flags & MF_DROPPED))
                                                             ^
p_inter.c:584:59: warning: overflow in implicit constant conversion [-Woverflow]
         if(!P_GiveWeapon(player, wp_sigil, special->flags & MF_DROPPED))
```

**Comment by camgunz** [comment] 2015-02-19 20:06
Yeah I think this is a solid plan.  Nice work ;).

**Comment by fabiangreffrath** [comment] 2015-02-19 21:00
Can't these be fixed by prepending `!!`, e.g. 
``
if (!P_GiveWeapon (player, wp_chaingun, !!(special->flags&MF_DROPPED)) )
``

**Comment by camgunz** [comment] 2015-02-19 21:13
It doesn't save you any space either, parentheses.

**Comment by fragglet** [comment] 2015-02-20 06:21
Ran all the statcheck tests with boolean compiled as an unsigned char. The only test that failed was mm09-512.lmp, which is a known bug (#368).

So I'm declaring this fixed.

**Closed by fragglet** 2015-02-20 06:21 UTC
