### ISSUE TITLE
Windows key = Alt

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#234] opened 2013-12-08 19:54 UTC
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/234/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2012-03-13 00:07:56:

I discovered that I can use the Windows key to strafe in Chocolate-Doom. I was tempted to play with the classic controls and I wanted to use Alt to strafe, but I pressed on the Windows key. Pressing the Windows key and then an arrow key didn't bring out the Windows menu. I also tried in Chocolate-Setup.exe, I pressed the Windows key in the "Configure keyboard" menu and it was changed to Alt. I confirmed that it was a bug in DosBox because it didn't strafe. I also think this key is ignored under DOS.

**Comment by jmtd** [comment] 2016-07-15 15:29
@AXDOOMER , I've put up a dev build of sdl2-branch here http://jmtd.net/tmp/chocolate-doom-sdl2-branch-win32-dbg.zip

Could you please let me know whether you still have this problem, and if sdl2-branch fixes it?

**Comment by AXDOOMER** [comment] 2016-07-17 01:43
Nothing changed. Windows threads the right Alt key as Ctrl + Alt so it does special characters.

**Comment by AXDOOMER** [comment] 2016-07-17 01:47
Misread the bug report. I have only a left Windows key on my keyboard, so I can't test this right now.

**Comment by jmtd** [comment] 2016-07-17 06:55
I didn't realise that this only applies to right Windows key...

**Comment by AXDOOMER** [comment] 2016-07-17 06:57
I have no idea if it's only for the right Windows key, but I should test before we close this bug report.

**Comment by AXDOOMER** [comment] 2016-07-17 18:07
Can't reproduce the bug on Windows 7.

**Comment by jmtd** [comment] 2016-07-17 22:08
Thanks for your efforts, @AXDOOMER !

**Closed by jmtd** 2016-07-17 22:08 UTC
Labels: input
