### ISSUE TITLE
User reporting process still does not terminate in Windows

### ISSUE THREAD

**Issue by haleyjd** [chocolate-doom/chocolate-doom#524] opened 2015-04-05 17:22 UTC
http://www.doomworld.com/vb/post/1358748

Complaint is that the application remains as a zombie process visible in task manager after being closed, a problem that was supposedly fixed earlier. Already had him try a recent git revision and he claims it is still happening.

**Comment by fragglet** [comment] 2015-04-05 19:32
Duplicate of #408?

**Closed** 2015-04-05 19:33 UTC
Labels: duplicate
