### ISSUE TITLE
Key binding

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#156] opened 2013-12-08 19:52 UTC
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/156/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-04-10 22:54:19:

Binding a key that is in the Other Keys menu to a action that is in the keyboard configuration menu should not set the same key to \(None\) in the Other Keys... menu.

**Comment by CapnClever** [comment] 2016-10-19 01:48
Does anyone else have a dedicated Break key to test this? I have two keyboards, one entirely without Break and one with a combination Pause/Break, and attempting to bind this key on the latter binds it to "PAUSE" anyway (which, in my own testing, can be held down to move forward for extended periods).

This seems like an extreme fringe case. Unless Linux keyboards typically come equipped with a dedicated Break key, Windows seems to only get Pause/Break (if that) and OSX doesn't sound like they have one either.

On the other hand, the original setup also appears to treat the F-keys in general as unbindable (binding nothing if you press any F-key down), nor will the game respond to such commands if you hardcode them into the config file. Technically, vanilla is functional with F-keys boys to actions, but those actions are effectively useless. Chocolate Doom could keep a list of keys that aren't allowed to be bound to any of the original keypresses and prevent their binding.

**Comment by chungy** [comment] 2016-10-19 03:30
As far as I know, PC-compatibles never had separate pause and break keys. Two labels for the same key, same scancode of course. There is no such thing as a "Linux keyboard" fwiw :P

**Comment by fragglet** [comment] 2016-10-19 03:32
> On the other hand, the original setup also appears to treat the F-keys in general as unbindable [...] Chocolate Doom could keep a list of keys that aren't allowed to be bound to any of the original keypresses and prevent their binding.

Please note that Chocolate Doom setup does not have a design goal of reproducing the vanilla setup tool's behavior. Beyond having a nostalgic look and feel it's its own thing.

In this case we are deliberately breaking vanilla behavior by adding the ability to rebind certain keys (weapon keys, function keys, etc.). So it's intended that we can rebind those keys and we shouldn't keep them as any kind of list that should be excluded.

After having read through this bug again I think I'm going to go ahead and close it unless there's a strong objection. The only (I think?) maybe-legitimate bug is with the pause key behavior and it might just be the case that it has some special operating system-level behavior that we don't have control over.

**Closed by fragglet** 2016-10-19 03:32 UTC
Labels: input
