### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by symbios24** [chocolate-doom/chocolate-doom#916] opened 2017-06-14 05:13 UTC
Hello i`m trying to install chocolate doom through the Retropie-Extra Scripts (https://github.com/zerojay/RetroPie-Extra) as i did it several times before with success, but the install keeps failing i`m getting this error "/home/pi/retropie-setup/tmp/build/chocolate-doom/src/chocolate-strife not found" ,is the chocolate doom github at the moment having any problems?

i have the log here:

Log started at: Wed 14 Jun 06:42:59 UTC 2017

= = = = = = = = = = = = = = = = = = = = =
Installing dependencies for 'chocolate-doom' : Chocolate Doom - Enhanced port of the official DOOM source
= = = = = = = = = = = = = = = = = = = = =

/home/pi/RetroPie-Setup/tmp/build/chocolate-doom /home/pi

= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'chocolate-doom' : Chocolate Doom - Enhanced port of the official DOOM source
= = = = = = = = = = = = = = = = = = = = =

git clone --recursive --depth 1 "https://github.com/chocolate-doom/chocolate-doom.git" "/home/pi/RetroPie-Setup/tmp/build/chocolate-doom"
Cloning into '/home/pi/RetroPie-Setup/tmp/build/chocolate-doom'...
/home/pi
/home/pi/RetroPie-Setup/tmp/build/chocolate-doom /home/pi

= = = = = = = = = = = = = = = = = = = = =
Building 'chocolate-doom' : Chocolate Doom - Enhanced port of the official DOOM source
= = = = = = = = = = = = = = = = = = = = =

configure.ac:17: installing 'autotools/compile'
configure.ac:13: installing 'autotools/config.guess'
configure.ac:13: installing 'autotools/config.sub'
configure.ac:111: installing 'autotools/install-sh'
configure.ac:111: installing 'autotools/missing'
opl/Makefile.am: installing 'autotools/depcomp'
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for ranlib... ranlib
checking for python... true
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SDL... yes
checking for SDLMIXER... yes
checking for SDLNET... no
configure: error: Package requirements (SDL2_net >= 2.0.0) were not met:

No package 'SDL2_net' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SDLNET_CFLAGS
and SDLNET_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for ranlib... ranlib
checking for python... true
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SDL... yes
checking for SDLMIXER... yes
checking for SDLNET... no
configure: error: Package requirements (SDL2_net >= 2.0.0) were not met:

No package 'SDL2_net' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SDLNET_CFLAGS
and SDLNET_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
/home/pi
Could not successfully build chocolate-doom - Chocolate Doom - Enhanced port of the official DOOM source (/home/pi/RetroPie-Setup/tmp/build/chocolate-doom/src/chocolate-strife not found).

Log ended at: Wed 14 Jun 06:44:25 UTC 2017
Total running time: 0 hours, 1 mins, 26 secs

Thanks

**Comment by symbios24** [comment] 2017-06-14 09:06
I found the solution this files were required for the installation "libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev" 
Can you include them in the Chocolate-Doom script??

**Comment by jmtd** [comment] 2017-06-14 10:38
> Can you include them in the Chocolate-Doom script to setup them automatically??

The script you are talking about is part of Retropie, not chocolate-doom, so the fix needs to be there.

**Comment by jmtd** [comment] 2017-06-14 10:40
This is the relevant repo/script https://github.com/zerojay/RetroPie-Extra/blob/3c0765f19450feb7aca06bdcc37e46cf18a64d57/scriptmodules/ports/chocolate-doom.sh

the issue is they have likely not updated the script since we switched the default branch to the SDL2 version of chocolate-doom.

**Comment by jmtd** [comment] 2017-06-14 10:42
I'm going to close this issue since it's reported upstream as https://github.com/zerojay/RetroPie-Extra/issues/213 and that's where the fix needs to happen

**Closed by jmtd** 2017-06-14 10:42 UTC

**Comment by symbios24** [comment] 2017-06-14 10:57
ok thanks,i reported it also in the  zerojay/RetroPie-Extra but i think is not so active there the scene

Thanks
